 /*-------------------------------------------------------------------------------
 * Module		: Port
 * File Name	: Port_PBcfg.h
 * Description	: post build configuration file for Port Module.
 * Author		: Mohamed salah-el-den
 * AR version	: V3.2.0
 * SW version	: V1.0.0
 -------------------------------------------------------------------------------*/

#include "../../Std_Types.h"
#include "../static_code/Port_types.h"
/*********************************************************************************************************
 * PORT module
 * 		PortConfigSet								(container)		1
 *	 		PortContainer							(container)		1.*		(container for each port)
 * 				PortNumberOfPortPins				(EcucIntegerParamDef)	(32)	(Pre-compile)
 * 				PortPin								(container)		1..*	(container for each pin)
 * 					PortPinDirection
 * 					PortPinDirectionChangeable
 * 					PortPinId
 * 					PortPinInitialMode
 * 					PortPinLevelValue
 * 					PortPinMode
 * 					PortPinModeChangeable
 * 		PortGeneral									(container)		1
 * 			PORT_DEV_ERROR_DETECT					(EcucBooleanParamDef)
 * 			PORT_SET_PIN_DIRECTION_API				(EcucBooleanParamDef)
 * 			PORT_SET_PIN_MODE_API					(EcucBooleanParamDef)
 * 			PORT_VERSION_INFO_API					(EcucBooleanParamDef)
 **********************************************************************************************************/


Port_ConfigType Port_Configuration = {
		{
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_OUT , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE},
				{PORT_PIN_IN , FALSE , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_HIGH , PORT_PIN_MODE_DIO , FALSE , PORT_INT_RES_DISABLE}
		}
};
